version: "2"
linters:
  default: none
  enable:
    - dupl
    - errcheck
    - exhaustive
    - goheader
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - mnd
    - prealloc
    - revive
    - staticcheck
    - unused
  settings:
    goheader:
      template-path: .goheader.template
    lll:
      line-length: 100
      tab-width: 4
  exclusions:
    generated: strict
    rules:
      - path: _test\.go
        linters:
          - dupl
          - gosec
formatters:
  enable:
    - goimports
  exclusions:
    generated: strict
