version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: unix
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - 386
    ldflags:
      - -s -w -X "main.versionString={{.Env.CLIVERSION}}"
    env:
      - CGO_ENABLED=0
  - id: windows
    goos:
      - windows
    goarch:
      - amd64
      - arm64
      - 386
    ldflags:
      - -s -w -X "main.versionString={{.Env.CLIVERSION}}"
    env:
      - CGO_ENABLED=0
archives:
  - id: windows
    formats:
      - "zip"
    ids:
      - windows
  - id: unix
    formats:
      - "tar.gz"
    ids:
      - unix
