before:
  hooks:
    - go mod tidy
builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
      - 386
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
